/*
 * This C file has been generated by smidump 0.4.8.
 * It is intended to be used with the NET-SNMP agent library.
 *
 * This C file is derived from the ICINGA-ICINGA2-MIB module.
 *
 * $Id$
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "icinga-icinga2-mib.h"

#include <ucd-snmp/asn1.h>
#include <ucd-snmp/snmp.h>
#include <ucd-snmp/snmp_api.h>
#include <ucd-snmp/snmp_impl.h>
#include <ucd-snmp/snmp_vars.h>

/*
 * Forward declaration of read methods for groups of scalars and tables:
 */

static unsigned char *
read_i2ObjectAttributes_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2GenericAttribute_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2HostAttributes_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2ServiceAttributes_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2UserAttributes_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2EndpointAttributes_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2ZoneAttributes_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_icinga2Status_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);

/*
 * Forward declaration of write methods for writable objects:
 */

static int
write_i2ObjectType_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2Name_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2StateType_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2DisplayName_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2HostName_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2ServiceName_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2StateService_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2NotificationType_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2UserPager_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2EndpointName_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2ZoneName_stub(int, u_char *, u_char, int, u_char *, oid *, int);

/*
 * Definitions of tags that are used internally to read/write
 * the selected object type. These tags should be unique.
 */

#define I2NOTIFICATIONTYPE               6

static oid i2ObjectAttributes_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 1};

struct variable i2ObjectAttributes_variables[] = {
    { I2NOTIFICATIONTYPE, ASN_INTEGER, RWRITE, read_i2ObjectAttributes_stub, 1, {6} },
};

#define I2OBJECTTYPE                     1
#define I2NAME                           3
#define I2STATETYPE                      4
#define I2DISPLAYNAME                    5
#define I2NOTES                          6
#define I2NOTESURL                       7
#define I2OUTPUT                         8
#define I2CHECKCOMMAND                   9
#define I2CHECKATTEMPT                   10
#define I2ENABLEACTIVECHECKS             11
#define I2ENABLEEVENTHANDLER             12
#define I2ENABLEFLAPPING                 13
#define I2ENABLENOTFICATIONS             14
#define I2ENABLEPASSIVECHECK             15
#define I2ENABLEPERFDATA                 16
#define I2ACTIVE                         17
#define I2GLOBAL                         18
#define I2ADDRESS                        19
#define I2ADDRESS6                       20
#define I2PARENT                         21
#define I2HAMODE                         22
#define I2LASTCHECK                      99
#define I2CHECKINTERVAL                  100
#define I2CHECKPERIOD                    101

static oid i2GenericAttribute_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 1, 0};

struct variable i2GenericAttribute_variables[] = {
    { I2OBJECTTYPE, ASN_INTEGER, RWRITE, read_i2GenericAttribute_stub, 1, {1} },
    { I2NAME, ASN_OCTET_STR, RWRITE, read_i2GenericAttribute_stub, 1, {3} },
    { I2STATETYPE, ASN_INTEGER, RWRITE, read_i2GenericAttribute_stub, 1, {4} },
    { I2DISPLAYNAME, ASN_OCTET_STR, RWRITE, read_i2GenericAttribute_stub, 1, {5} },
    { I2NOTES, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {6} },
    { I2NOTESURL, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {7} },
    { I2OUTPUT, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {8} },
    { I2CHECKCOMMAND, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {9} },
    { I2CHECKATTEMPT, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {10} },
    { I2ENABLEACTIVECHECKS, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {11} },
    { I2ENABLEEVENTHANDLER, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {12} },
    { I2ENABLEFLAPPING, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {13} },
    { I2ENABLENOTFICATIONS, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {14} },
    { I2ENABLEPASSIVECHECK, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {15} },
    { I2ENABLEPERFDATA, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {16} },
    { I2ACTIVE, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {17} },
    { I2GLOBAL, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {18} },
    { I2ADDRESS, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {19} },
    { I2ADDRESS6, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {20} },
    { I2PARENT, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {21} },
    { I2HAMODE, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {22} },
    { I2LASTCHECK, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {99} },
    { I2CHECKINTERVAL, ASN_INTEGER, RONLY, read_i2GenericAttribute_stub, 1, {100} },
    { I2CHECKPERIOD, ASN_OCTET_STR, RONLY, read_i2GenericAttribute_stub, 1, {101} },
};

#define I2HOSTNAME                       1
#define I2STATEHOST                      4

static oid i2HostAttributes_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 1, 1};

struct variable i2HostAttributes_variables[] = {
    { I2HOSTNAME, ASN_OCTET_STR, RWRITE, read_i2HostAttributes_stub, 1, {1} },
    { I2STATEHOST, ASN_INTEGER, RONLY, read_i2HostAttributes_stub, 1, {4} },
};

#define I2SERVICENAME                    1
#define I2STATESERVICE                   2

static oid i2ServiceAttributes_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 1, 2};

struct variable i2ServiceAttributes_variables[] = {
    { I2SERVICENAME, ASN_OCTET_STR, RWRITE, read_i2ServiceAttributes_stub, 1, {1} },
    { I2STATESERVICE, ASN_INTEGER, RWRITE, read_i2ServiceAttributes_stub, 1, {2} },
};

#define I2USERPAGER                      1

static oid i2UserAttributes_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 1, 10};

struct variable i2UserAttributes_variables[] = {
    { I2USERPAGER, ASN_OCTET_STR, RWRITE, read_i2UserAttributes_stub, 1, {1} },
};

#define I2ENDPOINTNAME                   1

static oid i2EndpointAttributes_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 1, 13};

struct variable i2EndpointAttributes_variables[] = {
    { I2ENDPOINTNAME, ASN_OCTET_STR, RWRITE, read_i2EndpointAttributes_stub, 1, {1} },
};

#define I2ZONENAME                       1

static oid i2ZoneAttributes_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 1, 14};

struct variable i2ZoneAttributes_variables[] = {
    { I2ZONENAME, ASN_OCTET_STR, RWRITE, read_i2ZoneAttributes_stub, 1, {1} },
};

#define I2DAEMONSTATUS                   1
#define I2CLUSTERSTATUS                  2

static oid icinga2Status_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 8};

struct variable icinga2Status_variables[] = {
    { I2DAEMONSTATUS, ASN_INTEGER, RONLY, read_icinga2Status_stub, 1, {1} },
    { I2CLUSTERSTATUS, ASN_INTEGER, RONLY, read_icinga2Status_stub, 1, {2} },
};



/*
 * Registration functions for the various MIB groups.
 */

int register_i2ObjectAttributes()
{
    return register_mib("i2ObjectAttributes",
         i2ObjectAttributes_variables,
         sizeof(struct variable),
         sizeof(i2ObjectAttributes_variables)/sizeof(struct variable),
         i2ObjectAttributes_base,
         sizeof(i2ObjectAttributes_base)/sizeof(oid));
};


int register_i2GenericAttribute()
{
    return register_mib("i2GenericAttribute",
         i2GenericAttribute_variables,
         sizeof(struct variable),
         sizeof(i2GenericAttribute_variables)/sizeof(struct variable),
         i2GenericAttribute_base,
         sizeof(i2GenericAttribute_base)/sizeof(oid));
};


int register_i2HostAttributes()
{
    return register_mib("i2HostAttributes",
         i2HostAttributes_variables,
         sizeof(struct variable),
         sizeof(i2HostAttributes_variables)/sizeof(struct variable),
         i2HostAttributes_base,
         sizeof(i2HostAttributes_base)/sizeof(oid));
};


int register_i2ServiceAttributes()
{
    return register_mib("i2ServiceAttributes",
         i2ServiceAttributes_variables,
         sizeof(struct variable),
         sizeof(i2ServiceAttributes_variables)/sizeof(struct variable),
         i2ServiceAttributes_base,
         sizeof(i2ServiceAttributes_base)/sizeof(oid));
};


int register_i2UserAttributes()
{
    return register_mib("i2UserAttributes",
         i2UserAttributes_variables,
         sizeof(struct variable),
         sizeof(i2UserAttributes_variables)/sizeof(struct variable),
         i2UserAttributes_base,
         sizeof(i2UserAttributes_base)/sizeof(oid));
};


int register_i2EndpointAttributes()
{
    return register_mib("i2EndpointAttributes",
         i2EndpointAttributes_variables,
         sizeof(struct variable),
         sizeof(i2EndpointAttributes_variables)/sizeof(struct variable),
         i2EndpointAttributes_base,
         sizeof(i2EndpointAttributes_base)/sizeof(oid));
};


int register_i2ZoneAttributes()
{
    return register_mib("i2ZoneAttributes",
         i2ZoneAttributes_variables,
         sizeof(struct variable),
         sizeof(i2ZoneAttributes_variables)/sizeof(struct variable),
         i2ZoneAttributes_base,
         sizeof(i2ZoneAttributes_base)/sizeof(oid));
};


int register_icinga2Status()
{
    return register_mib("icinga2Status",
         icinga2Status_variables,
         sizeof(struct variable),
         sizeof(icinga2Status_variables)/sizeof(struct variable),
         icinga2Status_base,
         sizeof(icinga2Status_base)/sizeof(oid));
};


/*
 * Read methods for groups of scalars and tables:
 */

static unsigned char *
read_i2ObjectAttributes_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2ObjectAttributes_t i2ObjectAttributes;

    /* call the user supplied function to retrieve values */

    read_i2ObjectAttributes(&i2ObjectAttributes);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2NOTIFICATIONTYPE:
        return (unsigned char *) &i2ObjectAttributes.i2NotificationType;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2GenericAttribute_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2GenericAttribute_t i2GenericAttribute;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2GenericAttribute(&i2GenericAttribute);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2OBJECTTYPE:
        return (unsigned char *) &i2GenericAttribute.i2ObjectType;

    case I2NAME:
        *var_len = i2GenericAttribute._i2NameLength;
        return (unsigned char *) i2GenericAttribute.i2Name;

    case I2STATETYPE:
        return (unsigned char *) &i2GenericAttribute.i2StateType;

    case I2DISPLAYNAME:
        *var_len = i2GenericAttribute._i2DisplayNameLength;
        return (unsigned char *) i2GenericAttribute.i2DisplayName;

    case I2NOTES:
        *var_len = i2GenericAttribute._i2NotesLength;
        return (unsigned char *) i2GenericAttribute.i2Notes;

    case I2NOTESURL:
        *var_len = i2GenericAttribute._i2NotesUrlLength;
        return (unsigned char *) i2GenericAttribute.i2NotesUrl;

    case I2OUTPUT:
        *var_len = i2GenericAttribute._i2OutputLength;
        return (unsigned char *) i2GenericAttribute.i2Output;

    case I2CHECKCOMMAND:
        *var_len = i2GenericAttribute._i2CheckCommandLength;
        return (unsigned char *) i2GenericAttribute.i2CheckCommand;

    case I2CHECKATTEMPT:
        return (unsigned char *) &i2GenericAttribute.i2CheckAttempt;

    case I2ENABLEACTIVECHECKS:
        return (unsigned char *) &i2GenericAttribute.i2EnableActiveChecks;

    case I2ENABLEEVENTHANDLER:
        return (unsigned char *) &i2GenericAttribute.i2EnableEventHandler;

    case I2ENABLEFLAPPING:
        return (unsigned char *) &i2GenericAttribute.i2EnableFlapping;

    case I2ENABLENOTFICATIONS:
        return (unsigned char *) &i2GenericAttribute.i2EnableNotfications;

    case I2ENABLEPASSIVECHECK:
        return (unsigned char *) &i2GenericAttribute.i2EnablePassiveCheck;

    case I2ENABLEPERFDATA:
        return (unsigned char *) &i2GenericAttribute.i2EnablePerfdata;

    case I2ACTIVE:
        return (unsigned char *) &i2GenericAttribute.i2Active;

    case I2GLOBAL:
        return (unsigned char *) &i2GenericAttribute.i2Global;

    case I2ADDRESS:
        *var_len = i2GenericAttribute._i2AddressLength;
        return (unsigned char *) i2GenericAttribute.i2Address;

    case I2ADDRESS6:
        *var_len = i2GenericAttribute._i2Address6Length;
        return (unsigned char *) i2GenericAttribute.i2Address6;

    case I2PARENT:
        *var_len = i2GenericAttribute._i2ParentLength;
        return (unsigned char *) i2GenericAttribute.i2Parent;

    case I2HAMODE:
        return (unsigned char *) &i2GenericAttribute.i2HaMode;

    case I2LASTCHECK:
        *var_len = i2GenericAttribute._i2LastCheckLength;
        return (unsigned char *) i2GenericAttribute.i2LastCheck;

    case I2CHECKINTERVAL:
        return (unsigned char *) &i2GenericAttribute.i2CheckInterval;

    case I2CHECKPERIOD:
        *var_len = i2GenericAttribute._i2CheckPeriodLength;
        return (unsigned char *) i2GenericAttribute.i2CheckPeriod;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2HostAttributes_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2HostAttributes_t i2HostAttributes;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2HostAttributes(&i2HostAttributes);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2HOSTNAME:
        *var_len = i2HostAttributes._i2HostNameLength;
        return (unsigned char *) i2HostAttributes.i2HostName;

    case I2STATEHOST:
        return (unsigned char *) &i2HostAttributes.i2StateHost;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2ServiceAttributes_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2ServiceAttributes_t i2ServiceAttributes;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2ServiceAttributes(&i2ServiceAttributes);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2SERVICENAME:
        *var_len = i2ServiceAttributes._i2ServiceNameLength;
        return (unsigned char *) i2ServiceAttributes.i2ServiceName;

    case I2STATESERVICE:
        return (unsigned char *) &i2ServiceAttributes.i2StateService;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2UserAttributes_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2UserAttributes_t i2UserAttributes;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2UserAttributes(&i2UserAttributes);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2USERPAGER:
        *var_len = i2UserAttributes._i2UserPagerLength;
        return (unsigned char *) i2UserAttributes.i2UserPager;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2EndpointAttributes_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2EndpointAttributes_t i2EndpointAttributes;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2EndpointAttributes(&i2EndpointAttributes);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2ENDPOINTNAME:
        *var_len = i2EndpointAttributes._i2EndpointNameLength;
        return (unsigned char *) i2EndpointAttributes.i2EndpointName;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2ZoneAttributes_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2ZoneAttributes_t i2ZoneAttributes;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2ZoneAttributes(&i2ZoneAttributes);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2ZONENAME:
        *var_len = i2ZoneAttributes._i2ZoneNameLength;
        return (unsigned char *) i2ZoneAttributes.i2ZoneName;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_icinga2Status_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static icinga2Status_t icinga2Status;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_icinga2Status(&icinga2Status);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2DAEMONSTATUS:
        return (unsigned char *) &icinga2Status.i2DaemonStatus;

    case I2CLUSTERSTATUS:
        return (unsigned char *) &icinga2Status.i2ClusterStatus;

    default:
         ERROR_MSG("");
    }

    return NULL;
}


/*
 * Forward declaration of write methods for writable objects:
 */

static int
write_i2ObjectType_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2Name_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2StateType_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2DisplayName_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2HostName_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2ServiceName_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2StateService_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2NotificationType_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2UserPager_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2EndpointName_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2ZoneName_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}


