/*							-- DO NOT EDIT --
 * Generated by smidump version 0.4.8:
 *   smidump -f scli KOBOLDMAKI-ICINGA2-MIB
 *
 * Derived from KOBOLDMAKI-ICINGA2-MIB:
 *   ICINGA2 MIB, see also at REVISION=LAST-UPDATED
 *
 * Revision 2016-10-20 23:59:
 *   WIP, add base fields.
 *
 * Revision 2015-12-25 00:01:
 *   initial version
 *
 * $Id$
 */

#include "koboldmaki-icinga2-mib.h"

GNetSnmpEnum const koboldmaki_icinga2_mib_enums_i2ObjectType[] = {
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_HOST,              "host" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_SERVICE,           "service" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_HOSTGROUP,         "hostgroup" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_SERVICEGROUP,      "servicegroup" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_HOSTESCALATION,    "hostescalation" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_SERVICEESCALATION, "serviceescalation" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_HOSTDEPENDENCY,    "hostdependency" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_SERVICEDEPENDENCY, "servicedependency" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_TIMEPERIOD,        "timeperiod" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_CONTACT,           "contact" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_CONTACTGROUP,      "contactgroup" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_COMMAND,           "command" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_ENDPOINT,          "endpoint" },
    { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE_ZONE,              "zone" },
    { 0, NULL }
};

GNetSnmpEnum const koboldmaki_icinga2_mib_enums_i2StateType[] = {
    { KOBOLDMAKI_ICINGA2_MIB_I2STATETYPE_STATETYPESOFT, "stateTypeSoft" },
    { KOBOLDMAKI_ICINGA2_MIB_I2STATETYPE_STATETYPEHARD, "stateTypeHard" },
    { 0, NULL }
};

GNetSnmpEnum const koboldmaki_icinga2_mib_enums_i2StateHost[] = {
    { KOBOLDMAKI_ICINGA2_MIB_I2STATEHOST_HOSTUP,   "hostUp" },
    { KOBOLDMAKI_ICINGA2_MIB_I2STATEHOST_HOSTDOWN, "hostDown" },
    { 0, NULL }
};

GNetSnmpEnum const koboldmaki_icinga2_mib_enums_i2StateService[] = {
    { KOBOLDMAKI_ICINGA2_MIB_I2STATESERVICE_SERVICEOK,       "serviceOK" },
    { KOBOLDMAKI_ICINGA2_MIB_I2STATESERVICE_SERVICEWARNING,  "serviceWarning" },
    { KOBOLDMAKI_ICINGA2_MIB_I2STATESERVICE_SERVICECRITICAL, "serviceCritical" },
    { KOBOLDMAKI_ICINGA2_MIB_I2STATESERVICE_SERVICEUNKNOWN,  "serviceUnknown" },
    { 0, NULL }
};

GNetSnmpEnum const koboldmaki_icinga2_mib_enums_i2NotificationType[] = {
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_DOWNTIMESTART,   "downtimeStart" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_DOWNTIMEEND,     "downtimeEnd" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_DOWNTIMEREMOVED, "downtimeRemoved" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_CUSTOM,          "custom" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_ACKNOWLEDGEMENT, "acknowledgement" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_PROBLEM,         "problem" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_RECOVERY,        "recovery" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_FLAPPINGSTART,   "flappingStart" },
    { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONTYPE_FLAPPINGEND,     "flappingEnd" },
    { 0, NULL }
};

GNetSnmpEnum const koboldmaki_icinga2_mib_enums_I2Boolean[] = {
    { KOBOLDMAKI_ICINGA2_MIB_I2BOOLEAN_FALSE, "false" },
    { KOBOLDMAKI_ICINGA2_MIB_I2BOOLEAN_TRUE,  "true" },
    { 0, NULL }
};


static guint32 const i2ObjectField[]
	= { KOBOLDMAKI_ICINGA2_MIB_I2OBJECTFIELD };
static guint32 const i2HostName[]
	= { KOBOLDMAKI_ICINGA2_MIB_I2HOSTNAME };
static guint32 const icinga2Type[]
	= { KOBOLDMAKI_ICINGA2_MIB_ICINGA2TYPE };
static guint32 const icinga2Notifications[]
	= { KOBOLDMAKI_ICINGA2_MIB_ICINGA2NOTIFICATIONS };
static guint32 const icinga2Traps[]
	= { KOBOLDMAKI_ICINGA2_MIB_ICINGA2TRAPS };
static guint32 const icinga2Groups[]
	= { KOBOLDMAKI_ICINGA2_MIB_ICINGA2GROUPS };
static guint32 const icinga2Conformance[]
	= { KOBOLDMAKI_ICINGA2_MIB_ICINGA2CONFORMANCE };
static guint32 const icinga2Compliance[]
	= { KOBOLDMAKI_ICINGA2_MIB_ICINGA2COMPLIANCE };

GNetSnmpIdentity const koboldmaki_icinga2_mib_identities[] = {
    { i2ObjectField,
      G_N_ELEMENTS(i2ObjectField),
      "i2ObjectField" },
    { i2HostName,
      G_N_ELEMENTS(i2HostName),
      "i2HostName" },
    { icinga2Type,
      G_N_ELEMENTS(icinga2Type),
      "icinga2Type" },
    { icinga2Notifications,
      G_N_ELEMENTS(icinga2Notifications),
      "icinga2Notifications" },
    { icinga2Traps,
      G_N_ELEMENTS(icinga2Traps),
      "icinga2Traps" },
    { icinga2Groups,
      G_N_ELEMENTS(icinga2Groups),
      "icinga2Groups" },
    { icinga2Conformance,
      G_N_ELEMENTS(icinga2Conformance),
      "icinga2Conformance" },
    { icinga2Compliance,
      G_N_ELEMENTS(icinga2Compliance),
      "icinga2Compliance" },
    { 0, 0, NULL }
};


static guint32 const i2NotificationHost[]
	= { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONHOST };
static guint32 const i2NotificationService[]
	= { KOBOLDMAKI_ICINGA2_MIB_I2NOTIFICATIONSERVICE };

GNetSnmpIdentity const koboldmaki_icinga2_mib_notifications[] = {
    { i2NotificationHost,
      G_N_ELEMENTS(i2NotificationHost),
      "i2NotificationHost" },
    { i2NotificationService,
      G_N_ELEMENTS(i2NotificationService),
      "i2NotificationService" },
    { 0, 0, NULL }
};


static guint32 const i2ObjectField_oid[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 1};

static GNetSnmpAttribute i2ObjectField_attr[] = {
    { 2, GNET_SNMP_VARBIND_TYPE_INTEGER32,
      KOBOLDMAKI_ICINGA2_MIB_I2OBJECTTYPE, "i2ObjectType",
       NULL,
      G_STRUCT_OFFSET(koboldmaki_icinga2_mib_i2ObjectField_t, i2ObjectType),
      0,
      GSNMP_ATTR_FLAG_WRITABLE },
    { 0, 0, 0, NULL }
};

static guint32 const icinga2Type_oid[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2};

static GNetSnmpAttribute icinga2Type_attr[] = {
    { 3, GNET_SNMP_VARBIND_TYPE_INTEGER32,
      KOBOLDMAKI_ICINGA2_MIB_I2STATETYPE, "i2StateType",
       NULL,
      G_STRUCT_OFFSET(koboldmaki_icinga2_mib_icinga2Type_t, i2StateType),
      0,
      GSNMP_ATTR_FLAG_WRITABLE },
    { 4, GNET_SNMP_VARBIND_TYPE_INTEGER32,
      KOBOLDMAKI_ICINGA2_MIB_I2STATEHOST, "i2StateHost",
       NULL,
      G_STRUCT_OFFSET(koboldmaki_icinga2_mib_icinga2Type_t, i2StateHost),
      0,
      0 },
    { 5, GNET_SNMP_VARBIND_TYPE_INTEGER32,
      KOBOLDMAKI_ICINGA2_MIB_I2STATESERVICE, "i2StateService",
       NULL,
      G_STRUCT_OFFSET(koboldmaki_icinga2_mib_icinga2Type_t, i2StateService),
      0,
      GSNMP_ATTR_FLAG_WRITABLE },
    { 0, 0, 0, NULL }
};


koboldmaki_icinga2_mib_i2ObjectField_t *
koboldmaki_icinga2_mib_new_i2ObjectField()
{
    koboldmaki_icinga2_mib_i2ObjectField_t *i2ObjectField;

    i2ObjectField = (koboldmaki_icinga2_mib_i2ObjectField_t *) g_malloc0(sizeof(koboldmaki_icinga2_mib_i2ObjectField_t) + sizeof(gpointer));
    return i2ObjectField;
}

static inline koboldmaki_icinga2_mib_i2ObjectField_t *
assign_i2ObjectField(GList *vbl)
{
    koboldmaki_icinga2_mib_i2ObjectField_t *i2ObjectField;
    char *p;

    i2ObjectField = koboldmaki_icinga2_mib_new_i2ObjectField();
    p = (char *) i2ObjectField + sizeof(koboldmaki_icinga2_mib_i2ObjectField_t);
    * (GList **) p = vbl;

    gnet_snmp_attr_assign(vbl, i2ObjectField_oid, G_N_ELEMENTS(i2ObjectField_oid),
                      i2ObjectField_attr, i2ObjectField);

    return i2ObjectField;
}

void
koboldmaki_icinga2_mib_get_i2ObjectField(GNetSnmp *s, koboldmaki_icinga2_mib_i2ObjectField_t **i2ObjectField, gint64 mask)
{
    GList *in = NULL, *out = NULL;
    static const guint32 _base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 1, 0};
    guint32 base[128];

    *i2ObjectField = NULL;
    memcpy(base, _base, sizeof(_base));

    gnet_snmp_attr_get(s, &in, base, 11, 10, i2ObjectField_attr, mask);

    out = gnet_snmp_sync_getnext(s, in);
    g_list_foreach(in, (GFunc) gnet_snmp_varbind_delete, NULL);
    g_list_free(in);
    if (out) {
        if (s->error_status != GNET_SNMP_PDU_ERR_NOERROR) {
            g_list_foreach(out, (GFunc) gnet_snmp_varbind_delete, NULL);
            g_list_free(out);
            return;
        }
        *i2ObjectField = assign_i2ObjectField(out);
    }
}

void
koboldmaki_icinga2_mib_set_i2ObjectField(GNetSnmp *s, koboldmaki_icinga2_mib_i2ObjectField_t *i2ObjectField, gint64 mask)
{
    GList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 1, 0, 0};

    gnet_snmp_attr_set(s, &in, base, 12, 10, i2ObjectField_attr, mask, i2ObjectField);

    out = gnet_snmp_sync_set(s, in);
    g_list_foreach(in, (GFunc) gnet_snmp_varbind_delete, NULL);
    g_list_free(in);
    if (out) {
        g_list_foreach(out, (GFunc) gnet_snmp_varbind_delete, NULL);
        g_list_free(out);
    }
}

void
koboldmaki_icinga2_mib_free_i2ObjectField(koboldmaki_icinga2_mib_i2ObjectField_t *i2ObjectField)
{
    GList *vbl;
    char *p;

    if (i2ObjectField) {
        p = (char *) i2ObjectField + sizeof(koboldmaki_icinga2_mib_i2ObjectField_t);
        vbl = * (GList **) p;
        g_list_foreach(vbl, (GFunc) gnet_snmp_varbind_delete, NULL);
        g_list_free(vbl);
        g_free(i2ObjectField);
    }
}

koboldmaki_icinga2_mib_icinga2Type_t *
koboldmaki_icinga2_mib_new_icinga2Type()
{
    koboldmaki_icinga2_mib_icinga2Type_t *icinga2Type;

    icinga2Type = (koboldmaki_icinga2_mib_icinga2Type_t *) g_malloc0(sizeof(koboldmaki_icinga2_mib_icinga2Type_t) + sizeof(gpointer));
    return icinga2Type;
}

static inline koboldmaki_icinga2_mib_icinga2Type_t *
assign_icinga2Type(GList *vbl)
{
    koboldmaki_icinga2_mib_icinga2Type_t *icinga2Type;
    char *p;

    icinga2Type = koboldmaki_icinga2_mib_new_icinga2Type();
    p = (char *) icinga2Type + sizeof(koboldmaki_icinga2_mib_icinga2Type_t);
    * (GList **) p = vbl;

    gnet_snmp_attr_assign(vbl, icinga2Type_oid, G_N_ELEMENTS(icinga2Type_oid),
                      icinga2Type_attr, icinga2Type);

    return icinga2Type;
}

void
koboldmaki_icinga2_mib_get_icinga2Type(GNetSnmp *s, koboldmaki_icinga2_mib_icinga2Type_t **icinga2Type, gint64 mask)
{
    GList *in = NULL, *out = NULL;
    static const guint32 _base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 0};
    guint32 base[128];

    *icinga2Type = NULL;
    memcpy(base, _base, sizeof(_base));

    gnet_snmp_attr_get(s, &in, base, 11, 10, icinga2Type_attr, mask);

    out = gnet_snmp_sync_getnext(s, in);
    g_list_foreach(in, (GFunc) gnet_snmp_varbind_delete, NULL);
    g_list_free(in);
    if (out) {
        if (s->error_status != GNET_SNMP_PDU_ERR_NOERROR) {
            g_list_foreach(out, (GFunc) gnet_snmp_varbind_delete, NULL);
            g_list_free(out);
            return;
        }
        *icinga2Type = assign_icinga2Type(out);
    }
}

void
koboldmaki_icinga2_mib_set_icinga2Type(GNetSnmp *s, koboldmaki_icinga2_mib_icinga2Type_t *icinga2Type, gint64 mask)
{
    GList *in = NULL, *out = NULL;
    static guint32 base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 2, 0, 0};

    gnet_snmp_attr_set(s, &in, base, 12, 10, icinga2Type_attr, mask, icinga2Type);

    out = gnet_snmp_sync_set(s, in);
    g_list_foreach(in, (GFunc) gnet_snmp_varbind_delete, NULL);
    g_list_free(in);
    if (out) {
        g_list_foreach(out, (GFunc) gnet_snmp_varbind_delete, NULL);
        g_list_free(out);
    }
}

void
koboldmaki_icinga2_mib_free_icinga2Type(koboldmaki_icinga2_mib_icinga2Type_t *icinga2Type)
{
    GList *vbl;
    char *p;

    if (icinga2Type) {
        p = (char *) icinga2Type + sizeof(koboldmaki_icinga2_mib_icinga2Type_t);
        vbl = * (GList **) p;
        g_list_foreach(vbl, (GFunc) gnet_snmp_varbind_delete, NULL);
        g_list_free(vbl);
        g_free(icinga2Type);
    }
}


