/*
 * This C header file has been generated by smidump 0.4.8.
 * It is intended to be used with the NET-SNMP package.
 *
 * This header is derived from the ICINGA2-MIB module.
 *
 * $Id$
 */

#ifndef _ICINGA2_MIB_H_
#define _ICINGA2_MIB_H_

#include <stdlib.h>

#ifdef HAVE_STDINT_H
#include <stdint.h>
#endif

/*
 * C type definitions for ICINGA2-MIB::i2ObjectAttributes.
 */

typedef struct i2ObjectAttributes {
    int32_t   *i2NotificationType;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    int32_t   __i2NotificationType;
} i2ObjectAttributes_t;

/*
 * C manager interface stubs for ICINGA2-MIB::i2ObjectAttributes.
 */

extern int
icinga2_mib_mgr_get_i2ObjectAttributes(struct snmp_session *s, i2ObjectAttributes_t **i2ObjectAttributes);

/*
 * C agent interface stubs for ICINGA2-MIB::i2ObjectAttributes.
 */

extern int
icinga2_mib_agt_read_i2ObjectAttributes(i2ObjectAttributes_t *i2ObjectAttributes);
extern int
icinga2_mib_agt_register_i2ObjectAttributes();

/*
 * C type definitions for ICINGA2-MIB::i2GenericAttribute.
 */

typedef struct i2GenericAttribute {
    int32_t   *i2ObjectType;
    u_char    *i2Name;
    size_t    _i2NameLength;
    int32_t   *i2StateType;
    u_char    *i2DisplayName;
    size_t    _i2DisplayNameLength;
    u_char    *i2Notes;
    size_t    _i2NotesLength;
    u_char    *i2NotesUrl;
    size_t    _i2NotesUrlLength;
    u_char    *i2Output;
    size_t    _i2OutputLength;
    u_char    *i2CheckCommand;
    size_t    _i2CheckCommandLength;
    int32_t   *i2CheckAttempt;
    int32_t   *i2EnableActiveChecks;
    int32_t   *i2EnableEventHandler;
    int32_t   *i2EnableFlapping;
    int32_t   *i2EnableNotfications;
    int32_t   *i2EnablePassiveCheck;
    int32_t   *i2EnablePerfdata;
    int32_t   *i2Active;
    int32_t   *i2Global;
    u_char    *i2Address;
    size_t    _i2AddressLength;
    u_char    *i2Address6;
    size_t    _i2Address6Length;
    u_char    *i2Parent;
    size_t    _i2ParentLength;
    int32_t   *i2HaMode;
    u_char    *i2LastCheck;
    size_t    _i2LastCheckLength;
    int32_t   *i2CheckInterval;
    u_char    *i2CheckPeriod;
    size_t    _i2CheckPeriodLength;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    int32_t   __i2ObjectType;
    u_char    __i2Name[127];
    int32_t   __i2StateType;
    u_char    __i2DisplayName[127];
    u_char    __i2Notes[127];
    u_char    __i2NotesUrl[127];
    u_char    __i2Output[127];
    u_char    __i2CheckCommand[127];
    int32_t   __i2CheckAttempt;
    int32_t   __i2EnableActiveChecks;
    int32_t   __i2EnableEventHandler;
    int32_t   __i2EnableFlapping;
    int32_t   __i2EnableNotfications;
    int32_t   __i2EnablePassiveCheck;
    int32_t   __i2EnablePerfdata;
    int32_t   __i2Active;
    int32_t   __i2Global;
    u_char    __i2Address[127];
    u_char    __i2Address6[127];
    u_char    __i2Parent[127];
    int32_t   __i2HaMode;
    u_char    __i2LastCheck[65535];
    int32_t   __i2CheckInterval;
    u_char    __i2CheckPeriod[127];
} i2GenericAttribute_t;

/*
 * C manager interface stubs for ICINGA2-MIB::i2GenericAttribute.
 */

extern int
icinga2_mib_mgr_get_i2GenericAttribute(struct snmp_session *s, i2GenericAttribute_t **i2GenericAttribute);

/*
 * C agent interface stubs for ICINGA2-MIB::i2GenericAttribute.
 */

extern int
icinga2_mib_agt_read_i2GenericAttribute(i2GenericAttribute_t *i2GenericAttribute);
extern int
icinga2_mib_agt_register_i2GenericAttribute();

/*
 * C type definitions for ICINGA2-MIB::i2HostAttributes.
 */

typedef struct i2HostAttributes {
    u_char    *i2HostName;
    size_t    _i2HostNameLength;
    int32_t   *i2StateHost;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    u_char    __i2HostName[127];
    int32_t   __i2StateHost;
} i2HostAttributes_t;

/*
 * C manager interface stubs for ICINGA2-MIB::i2HostAttributes.
 */

extern int
icinga2_mib_mgr_get_i2HostAttributes(struct snmp_session *s, i2HostAttributes_t **i2HostAttributes);

/*
 * C agent interface stubs for ICINGA2-MIB::i2HostAttributes.
 */

extern int
icinga2_mib_agt_read_i2HostAttributes(i2HostAttributes_t *i2HostAttributes);
extern int
icinga2_mib_agt_register_i2HostAttributes();

/*
 * C type definitions for ICINGA2-MIB::i2ServiceAttributes.
 */

typedef struct i2ServiceAttributes {
    u_char    *i2ServiceName;
    size_t    _i2ServiceNameLength;
    int32_t   *i2StateService;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    u_char    __i2ServiceName[127];
    int32_t   __i2StateService;
} i2ServiceAttributes_t;

/*
 * C manager interface stubs for ICINGA2-MIB::i2ServiceAttributes.
 */

extern int
icinga2_mib_mgr_get_i2ServiceAttributes(struct snmp_session *s, i2ServiceAttributes_t **i2ServiceAttributes);

/*
 * C agent interface stubs for ICINGA2-MIB::i2ServiceAttributes.
 */

extern int
icinga2_mib_agt_read_i2ServiceAttributes(i2ServiceAttributes_t *i2ServiceAttributes);
extern int
icinga2_mib_agt_register_i2ServiceAttributes();

/*
 * C type definitions for ICINGA2-MIB::i2UserAttributes.
 */

typedef struct i2UserAttributes {
    u_char    *i2UserPager;
    size_t    _i2UserPagerLength;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    u_char    __i2UserPager[127];
} i2UserAttributes_t;

/*
 * C manager interface stubs for ICINGA2-MIB::i2UserAttributes.
 */

extern int
icinga2_mib_mgr_get_i2UserAttributes(struct snmp_session *s, i2UserAttributes_t **i2UserAttributes);

/*
 * C agent interface stubs for ICINGA2-MIB::i2UserAttributes.
 */

extern int
icinga2_mib_agt_read_i2UserAttributes(i2UserAttributes_t *i2UserAttributes);
extern int
icinga2_mib_agt_register_i2UserAttributes();

/*
 * C type definitions for ICINGA2-MIB::i2EndpointAttributes.
 */

typedef struct i2EndpointAttributes {
    u_char    *i2EndpointName;
    size_t    _i2EndpointNameLength;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    u_char    __i2EndpointName[127];
} i2EndpointAttributes_t;

/*
 * C manager interface stubs for ICINGA2-MIB::i2EndpointAttributes.
 */

extern int
icinga2_mib_mgr_get_i2EndpointAttributes(struct snmp_session *s, i2EndpointAttributes_t **i2EndpointAttributes);

/*
 * C agent interface stubs for ICINGA2-MIB::i2EndpointAttributes.
 */

extern int
icinga2_mib_agt_read_i2EndpointAttributes(i2EndpointAttributes_t *i2EndpointAttributes);
extern int
icinga2_mib_agt_register_i2EndpointAttributes();

/*
 * C type definitions for ICINGA2-MIB::i2ZoneAttributes.
 */

typedef struct i2ZoneAttributes {
    u_char    *i2ZoneName;
    size_t    _i2ZoneNameLength;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    u_char    __i2ZoneName[127];
} i2ZoneAttributes_t;

/*
 * C manager interface stubs for ICINGA2-MIB::i2ZoneAttributes.
 */

extern int
icinga2_mib_mgr_get_i2ZoneAttributes(struct snmp_session *s, i2ZoneAttributes_t **i2ZoneAttributes);

/*
 * C agent interface stubs for ICINGA2-MIB::i2ZoneAttributes.
 */

extern int
icinga2_mib_agt_read_i2ZoneAttributes(i2ZoneAttributes_t *i2ZoneAttributes);
extern int
icinga2_mib_agt_register_i2ZoneAttributes();


typedef struct icinga2_mib {
    i2ObjectAttributes_t	i2ObjectAttributes;
    i2GenericAttribute_t	i2GenericAttribute;
    i2HostAttributes_t	i2HostAttributes;
    i2ServiceAttributes_t	i2ServiceAttributes;
    i2UserAttributes_t	i2UserAttributes;
    i2EndpointAttributes_t	i2EndpointAttributes;
    i2ZoneAttributes_t	i2ZoneAttributes;
} icinga2_mib_t;

/*
 * Initialization function:
 */

void icinga2_mib_agt_init(void);

#endif /* _ICINGA2_MIB_H_ */
