/*
 * This C file has been generated by smidump 0.4.8.
 * It is intended to be used with the NET-SNMP agent library.
 *
 * This C file is derived from the KOBOLDMAKI-ICINGA2-MIB module.
 *
 * $Id$
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "koboldmaki-icinga2-mib.h"

#include <ucd-snmp/asn1.h>
#include <ucd-snmp/snmp.h>
#include <ucd-snmp/snmp_api.h>
#include <ucd-snmp/snmp_impl.h>
#include <ucd-snmp/snmp_vars.h>

/*
 * Forward declaration of read methods for groups of scalars and tables:
 */

static unsigned char *
read_i2Field_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2HostField_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
static unsigned char *
read_i2ServiceField_stub(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);

/*
 * Forward declaration of write methods for writable objects:
 */

static int
write_i2ObjectType_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2DisplayName_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2StateType_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2HostName_stub(int, u_char *, u_char, int, u_char *, oid *, int);
static int
write_i2StateService_stub(int, u_char *, u_char, int, u_char *, oid *, int);

/*
 * Definitions of tags that are used internally to read/write
 * the selected object type. These tags should be unique.
 */


#define I2OBJECTTYPE                     1
#define I2DISPLAYNAME                    2
#define I2STATETYPE                      3

static oid i2Field_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 1, 0};

struct variable i2Field_variables[] = {
    { I2OBJECTTYPE, ASN_INTEGER, RWRITE, read_i2Field_stub, 1, {1} },
    { I2DISPLAYNAME, ASN_OCTET_STR, RWRITE, read_i2Field_stub, 1, {2} },
    { I2STATETYPE, ASN_INTEGER, RWRITE, read_i2Field_stub, 1, {3} },
};

#define I2HOSTNAME                       1
#define I2STATEHOST                      4

static oid i2HostField_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 1, 1};

struct variable i2HostField_variables[] = {
    { I2HOSTNAME, ASN_OCTET_STR, RWRITE, read_i2HostField_stub, 1, {1} },
    { I2STATEHOST, ASN_INTEGER, RONLY, read_i2HostField_stub, 1, {4} },
};

#define I2STATESERVICE                   2

static oid i2ServiceField_base[] = {1, 3, 6, 1, 4, 1, 12483, 999, 2, 1, 2};

struct variable i2ServiceField_variables[] = {
    { I2STATESERVICE, ASN_INTEGER, RWRITE, read_i2ServiceField_stub, 1, {2} },
};



/*
 * Registration functions for the various MIB groups.
 */

int register_i2ObjectField()
{
    return register_mib("i2ObjectField",
         i2ObjectField_variables,
         sizeof(struct variable),
         sizeof(i2ObjectField_variables)/sizeof(struct variable),
         i2ObjectField_base,
         sizeof(i2ObjectField_base)/sizeof(oid));
};


int register_i2Field()
{
    return register_mib("i2Field",
         i2Field_variables,
         sizeof(struct variable),
         sizeof(i2Field_variables)/sizeof(struct variable),
         i2Field_base,
         sizeof(i2Field_base)/sizeof(oid));
};


int register_i2HostField()
{
    return register_mib("i2HostField",
         i2HostField_variables,
         sizeof(struct variable),
         sizeof(i2HostField_variables)/sizeof(struct variable),
         i2HostField_base,
         sizeof(i2HostField_base)/sizeof(oid));
};


int register_i2ServiceField()
{
    return register_mib("i2ServiceField",
         i2ServiceField_variables,
         sizeof(struct variable),
         sizeof(i2ServiceField_variables)/sizeof(struct variable),
         i2ServiceField_base,
         sizeof(i2ServiceField_base)/sizeof(oid));
};


/*
 * Read methods for groups of scalars and tables:
 */

static unsigned char *
read_i2Field_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2Field_t i2Field;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2Field(&i2Field);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2OBJECTTYPE:
        return (unsigned char *) &i2Field.i2ObjectType;

    case I2DISPLAYNAME:
        *var_len = i2Field._i2DisplayNameLength;
        return (unsigned char *) i2Field.i2DisplayName;

    case I2STATETYPE:
        return (unsigned char *) &i2Field.i2StateType;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2HostField_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2HostField_t i2HostField;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2HostField(&i2HostField);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2HOSTNAME:
        *var_len = i2HostField._i2HostNameLength;
        return (unsigned char *) i2HostField.i2HostName;

    case I2STATEHOST:
        return (unsigned char *) &i2HostField.i2StateHost;

    default:
         ERROR_MSG("");
    }

    return NULL;
}

static unsigned char *
read_i2ServiceField_stub(struct variable *vp,
    oid     *name,
    size_t  *length,
    int     exact,
    size_t  *var_len,
    WriteMethod **write_method)
{
    static i2ServiceField_t i2ServiceField;

    /* check whether the instance identifier is valid */

    if (header_generic(vp, name, length, exact, var_len,
                       write_method) == MATCH_FAILED) {
        return NULL;
    }

    /* call the user supplied function to retrieve values */

    read_i2ServiceField(&i2ServiceField);

    /* return the current value of the variable */

    switch (vp->magic) {

    case I2STATESERVICE:
        return (unsigned char *) &i2ServiceField.i2StateService;

    default:
         ERROR_MSG("");
    }

    return NULL;
}


/*
 * Forward declaration of write methods for writable objects:
 */

static int
write_i2ObjectType_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2DisplayName_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2StateType_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2HostName_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}

static int
write_i2StateService_stub(int action,
    u_char   *var_val,
    u_char   var_val_type,
    int      var_val_len,
    u_char   *statP,
    oid      *name,
    int      name_len)
{
    return SNMP_ERR_NOERROR;
}


