/*
 * This C header file has been generated by smidump 0.4.8.
 * It is intended to be used with the NET-SNMP package.
 *
 * This header is derived from the KOBOLDMAKI-ICINGA2-MIB module.
 *
 * $Id$
 */

#ifndef _KOBOLDMAKI_ICINGA2_MIB_H_
#define _KOBOLDMAKI_ICINGA2_MIB_H_

#include <stdlib.h>

#ifdef HAVE_STDINT_H
#include <stdint.h>
#endif

/*
 * C type definitions for KOBOLDMAKI-ICINGA2-MIB::i2Field.
 */

typedef struct i2Field {
    int32_t   *i2ObjectType;
    u_char    *i2DisplayName;
    size_t    _i2DisplayNameLength;
    int32_t   *i2StateType;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    int32_t   __i2ObjectType;
    u_char    __i2DisplayName[127];
    int32_t   __i2StateType;
} i2Field_t;

/*
 * C manager interface stubs for KOBOLDMAKI-ICINGA2-MIB::i2Field.
 */

extern int
koboldmaki_icinga2_mib_mgr_get_i2Field(struct snmp_session *s, i2Field_t **i2Field);

/*
 * C agent interface stubs for KOBOLDMAKI-ICINGA2-MIB::i2Field.
 */

extern int
koboldmaki_icinga2_mib_agt_read_i2Field(i2Field_t *i2Field);
extern int
koboldmaki_icinga2_mib_agt_register_i2Field();

/*
 * C type definitions for KOBOLDMAKI-ICINGA2-MIB::i2HostField.
 */

typedef struct i2HostField {
    u_char    *i2HostName;
    size_t    _i2HostNameLength;
    int32_t   *i2StateHost;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    u_char    __i2HostName[127];
    int32_t   __i2StateHost;
} i2HostField_t;

/*
 * C manager interface stubs for KOBOLDMAKI-ICINGA2-MIB::i2HostField.
 */

extern int
koboldmaki_icinga2_mib_mgr_get_i2HostField(struct snmp_session *s, i2HostField_t **i2HostField);

/*
 * C agent interface stubs for KOBOLDMAKI-ICINGA2-MIB::i2HostField.
 */

extern int
koboldmaki_icinga2_mib_agt_read_i2HostField(i2HostField_t *i2HostField);
extern int
koboldmaki_icinga2_mib_agt_register_i2HostField();

/*
 * C type definitions for KOBOLDMAKI-ICINGA2-MIB::i2ServiceField.
 */

typedef struct i2ServiceField {
    int32_t   *i2StateService;
    void      *_clientData;		/* pointer to client data structure */

    /* private space to hold actual values */

    int32_t   __i2StateService;
} i2ServiceField_t;

/*
 * C manager interface stubs for KOBOLDMAKI-ICINGA2-MIB::i2ServiceField.
 */

extern int
koboldmaki_icinga2_mib_mgr_get_i2ServiceField(struct snmp_session *s, i2ServiceField_t **i2ServiceField);

/*
 * C agent interface stubs for KOBOLDMAKI-ICINGA2-MIB::i2ServiceField.
 */

extern int
koboldmaki_icinga2_mib_agt_read_i2ServiceField(i2ServiceField_t *i2ServiceField);
extern int
koboldmaki_icinga2_mib_agt_register_i2ServiceField();


typedef struct koboldmaki_icinga2_mib {
    i2Field_t	i2Field;
    i2HostField_t	i2HostField;
    i2ServiceField_t	i2ServiceField;
} koboldmaki_icinga2_mib_t;

/*
 * Initialization function:
 */

void koboldmaki_icinga2_mib_agt_init(void);

#endif /* _KOBOLDMAKI_ICINGA2_MIB_H_ */
